### ISSUE TITLE
Please do not use bundled org.elasticsearch.common.collect.ImmutableList

### ISSUE THREAD

**Issue by Hubbitus** [imotov/elasticsearch-analysis-morphology#20]
On Fedora you plugin failed to start with (check elasticsearch 1.6 and 1.7.1):

```
Sep  9 18:52:53 hubbitus elasticsearch: SEVERE: Exception
Sep  9 18:52:53 hubbitus elasticsearch: java.lang.NoClassDefFoundError: org/elasticsearch/common/collect/ImmutableList
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.plugin.analysis.morphology.AnalysisMorphologyPlugin.modules(AnalysisMorphologyPlugin.java:45)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.plugins.PluginsService.modules(PluginsService.java:222)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.plugins.PluginsModule.spawnModules(PluginsModule.java:51)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:182)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
Sep  9 18:52:53 hubbitus elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Sep  9 18:52:53 hubbitus elasticsearch: Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.collect.ImmutableList
Sep  9 18:52:53 hubbitus elasticsearch: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Sep  9 18:52:53 hubbitus elasticsearch: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Sep  9 18:52:53 hubbitus elasticsearch: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Sep  9 18:52:53 hubbitus elasticsearch: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Sep  9 18:52:53 hubbitus elasticsearch: ... 9 more
```

I assume because all [bundled stuff removed](https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries) from lib directory in packaging.

But simple replacing import org.elasticsearch.common.collect.ImmutableList by com.google.common.collect.ImmutableList and adding dependency to guava:

```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0-rc1</version>
        </dependency>
```

fix problem (at least for elastic 1.7.1).

**Comment by Hubbitus** [comment]
Its similar to https://github.com/elastic/elasticsearch/issues/1779

**Comment by imotov** [comment]
Guava was removed in v5.0.0, so this is no longer a relevant issue. Closing.
