### ISSUE TITLE
Elasticsearch 2.3.2 support

### ISSUE THREAD

**Issue by AnatolyRugalev** [imotov/elasticsearch-analysis-morphology#32]
Can you please release version for Elasticsearch 2.3.2?

And why every minor elasticsearch version requires new version of plugin? Is backwards compatibility possible at all? May be I can install 2.3.1 plugins version to elasticsearch 2.3.2 somehow?

Thank you.

**Comment by alexcustos** [comment]
Usually you can bump the minor version without any issues. This is a Maven project and version can be updated in pom.xml. To compile and install just execute:
```
mvn package
plugin install file:target/releases/elasticsearch-analysis-morphology-2.3.2.zip
```

**Comment by AnatolyRugalev** [comment]
@alexcustos thank you, I will try this out

**Comment by MaxJust** [comment]
Hi, I try to use `mvn package`
and got this:
```
ownloading: http://repo1.maven.org/maven2/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
106K downloaded  (xml-apis-1.0.b2.jar)
247K downloaded  (junit-4.10.jar)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4': Unable to load the mojo 'com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4' in the plugin 'com.carrotsearch.randomizedtesting:junit4-maven-plugin'. A required class is missing: Lorg/apache/maven/repository/RepositorySystem;
org.apache.maven.repository.RepositorySystem
```

can anybody help to solve this?

**Comment by alexcustos** [comment]
@MaxJust I think you should delete ~/.m2 cache directory, and then try again. If not check your environment. I have successfully built it on:
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T14:57:37+03:00)
Maven home: /usr/share/maven-bin-3.3
Java version: 1.7.0_101, vendor: Oracle Corporation
Java home: /opt/icedtea-bin-7.2.6.6/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.6-gentoo", arch: "amd64", family: "unix"
```

**Comment by MaxJust** [comment]
I have update  maven to version 3.3.9 remove ~/.m2,  and got that error:
```
Executing 1 suite with 1 JVM.

Started J0 PID(15463@index1).
Suite: org.elasticsearch.index.analysis.morphology.SimpleMorphologyAnalysisTests
ERROR   0.00s | SimpleMorphologyAnalysisTests (suite) <<<
   > Throwable #1: java.lang.RuntimeException: don't run elasticsearch as root.
   >    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:93)
   >    at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:85)
   >    at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:99)
   >    at java.lang.Class.forName0(Native Method)
   >    at java.lang.Class.forName(Class.java:348)
Completed [1/1 (1!)] in 0.31s, 0 tests, 1 error <<< FAILURES!

Tests with failures [seed: 1FAF31FE4C71AC02]:
  - org.elasticsearch.index.analysis.morphology.SimpleMorphologyAnalysisTests (suite)
```

**Comment by alexcustos** [comment]
@MaxJust It seems it's all fine now. The only problem is the exception: "**don't** run elasticsearch as **root**". You must compile it as a normal user, then install as root.

**Comment by imotov** [comment]
Done

**Comment by AnatolyRugalev** [comment]
Thank you!

вт, 17 мая 2016 г. в 17:30, Igor Motov <notifications@github.com>:
