### ISSUE TITLE
Error injecting constructor

### ISSUE THREAD

**Issue by luisbaia** [imotov/elasticsearch-analysis-morphology#34]
We have a cluster with several nodes running on elasticsearch 1.7. For testing purposes at this moment no document is being analyzed with that addon. I can also assure we installed the proper version of the plugin according to our elasticsearch version.
After installing the addon on the first node and we start it up everything work as intended. However, after installing it on the second node and we try to start it up we get the following error:

"""
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NumberFormatException: For input string: "671904704682572"
  at org.elasticsearch.indices.analysis.morphology.MorphologyIndicesAnalysis.<init>(Unknown Source)
  while locating org.elasticsearch.indices.analysis.morphology.MorphologyIndicesAnalysis

1 error
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:210)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.NumberFormatException: For input string: "671904704682572"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.apache.lucene.morphology.MorphologyImpl.readSeparators(MorphologyImpl.java:196)
        at org.apache.lucene.morphology.MorphologyImpl.readFromInputStream(MorphologyImpl.java:145)
        at org.apache.lucene.morphology.MorphologyImpl.<init>(MorphologyImpl.java:38)
        at org.apache.lucene.morphology.LuceneMorphology.<init>(LuceneMorphology.java:32)
        at org.apache.lucene.morphology.russian.RussianLuceneMorphology.<init>(RussianLuceneMorphology.java:25)
        at org.apache.lucene.morphology.russian.RussianAnalyzer.<init>(RussianAnalyzer.java:25)
        at org.elasticsearch.indices.analysis.morphology.MorphologyIndicesAnalysis.<init>(MorphologyIndicesAnalysis.java:48)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        ... 9 more
"""

Apparently, when initializing the morphology plugin, at some point it tries to convert that string "671904704682572" to an int, which will fail given the dimension of the number. Since the analyzer is not being used to analyze any field, that string does not belong to any document. Even after looking at the code of the plugin, I do not understand exactly where does this number come from.
Any insight about this odd problem would be greatly appreciated.

The best regards

**Comment by imotov** [comment]
@luisbaia could you run `sha1` on all files in the directory where you installed the plugin on the second node and make sure they match the following:

```
~/Software/elasticsearch-1.7.5/plugins/analysis-morphology› shasum *
09abac7050a3ba85389274c8bb81cfba66e66330  elasticsearch-analysis-morphology-1.2.1.jar
a6b23376bcd49cd416546e9420c06e498ca26747  english-4.10.0.jar
89866a78e5b85291ab9e98ff2a8b964bd1083169  morph-4.10.0.jar
7d484cae85f138eb722e15a46d7ec731911ac09e  russian-4.10.0.jar
```

I think the `russian-4.10.0.jar` is corrupted on your second node and this is causing errors reading one of the dictionary files (org/apache/lucene/morphology/russian/morph.info to be specific).

**Comment by luisbaia** [comment]
Actually, my hashes are completely different for the four files

689f6691cb0c8b83e10b1682d50f6c75 ...\elasticsearch-analysis-morphology-1.2.1\elasticsearch-analysis-morphology-1.2.1.jar
a4a93fd776cddf229d5bc137616a2234 ...\elasticsearch-analysis-morphology-1.2.1\english-4.10.0.jar
6da7f1a795135f94a8737dfa13f083c1 ...\elasticsearch-analysis-morphology-1.2.1\morph-4.10.0.jar
7ebfdfffd78ac9049a9d4c2e372e0749 ...\elasticsearch-analysis-morphology-1.2.1\russian-4.10.0.jar

I am using the 1.2.1 version of the plugin. Any reason for the different hashes?

**Comment by imotov** [comment]
Are they at least the same on both nodes?
