### ISSUE TITLE
вышел ES5.2.1

### ISSUE THREAD

**Issue by greenx** [imotov/elasticsearch-analysis-morphology#38]
/usr/share/elasticsearch/bin/elasticsearch-plugin list
analysis-morphology
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-morphology] is incompatible with Elasticsearch [5.2.1]. Was designed for version [5.2.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
        at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:64)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by imotov** [comment]
Выпустил 5.2.1

**Comment by greenx** [comment]
А зачем ты так делаешь? Не проще указать совместимость как 5.х?

**Comment by imotov** [comment]
> Не проще указать совместимость как 5.х?

Если бы это было возможно, то так, действительно, было бы проще. Но насколько я понимаю, требуется [точное указание версии](https://github.com/elastic/elasticsearch/blob/7560101ec73331acb39a042bde6130e59e4bb630/core/src/main/java/org/elasticsearch/plugins/PluginInfo.java#L107). Если у Вас есть идеи по тому, как это обойти - то делитесь.
