### ISSUE TITLE
ElasticSearch v5.4.2 Install error

### ISSUE THREAD

**Issue by BakhtiyorRuziev** [imotov/elasticsearch-analysis-morphology#41]
When I install in my instance show this error:

root@xxx:/var/www/topvideo# /usr/share/elasticsearch/bin/elasticsearch-plugin  install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.4.2/elasticsearch-analysis-morphology-5.4.2.zip
-> Downloading http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.4.2/elasticsearch-analysis-morphology-5.4.2.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [analysis-morphology] is incompatible with version [5.4.2]; was designed for version [5.4.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:428)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:495)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:199)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by imotov** [comment]
Yep. Sorry, I messed this one up. I have released 5.4.2.1 with the fix.
