### ISSUE TITLE
Install error with 5.6.8 on FreeBSD 10.4

### ISSUE THREAD

**Issue by gessel** [imotov/elasticsearch-analysis-morphology#54]
# /usr/local/bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.8/elasticsearch-analysis-morphology-5.6.8.zip
-> Downloading http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.8/elasticsearch-analysis-morphology-5.6.8.zip
[=================================================] 100%   
```
Exception in thread "main" java.lang.IllegalArgumentException: property [elasticsearch.version] is missing for plugin [head]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:135)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:335)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:545)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:527)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```
running:
elasticsearch-plugin-head-2015.12.16 =   up-to-date with index
elasticsearch5-5.6.8_5             =   up-to-date with index

**Comment by imotov** [comment]
The error says: 

> Exception in thread "main" java.lang.IllegalArgumentException: property [elasticsearch.version] is missing for plugin [**head**]

So, the issue seems to be in another plugin. Which plugin head are you running? The only one that I know is https://github.com/mobz/elasticsearch-head But if you check it's [web site](https://github.com/mobz/elasticsearch-head#running-as-a-plugin-of-elasticsearch-deprecated) you will see that 

> for Elasticsearch 5.x: site plugins are not supported.

**Comment by gessel** [comment]
This one for FreeBSD - 
https://www.freshports.org/textproc/elasticsearch-plugin-head/
It may be exactly as you say, there's a mention of compatibility with 1 and 2.

**Comment by imotov** [comment]
Yes, it looks like it's the repackaged version of the same plugin. It's not going to work with 5.x, unfortunately.

**Comment by gessel** [comment]
Poopers, but thanks for the expert insight!
